// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct InstanceData{
	float3 position;
	float4 rotation;
	float scale;
};

RWStructuredBuffer<InstanceData> _iData;

[numthreads(1024,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	InstanceData data = _iData[id.x];
	data.position.y -= 0.1;
	if(data.position.y < -100)
		data.position.y = 100;

	_iData[id.x] = data;
}